### ISSUE TITLE
`Guard::unlock` leaves `Qutex` locked

### ISSUE THREAD

**Issue by JohnColanduoni** [cogciprocate/qutex#2]
The implementation of [`Guard::unlock`](https://github.com/cogciprocate/qutex/blob/6bfd7d0d95d90111d15e9f1d16befec74a1b649a/src/qutex.rs#L28) actually leaves the lock still locked by canceling the `Drop` implementation for `Guard`. I believe a call to `qutex.direct_unlock()` is needed after the `mem::forget` for the function to work as intended.

**Comment by c0gent** [comment]
You appear to be the first person to actually use `Guard::unlock`. Thanks!

**Comment by JohnColanduoni** [comment]
Awesome, thanks!
